### ISSUE TITLE
Rotation caused by maxSize writes '%DATE%' instead of writing date

### ISSUE THREAD

**Issue by R1D3R175** [winstonjs/winston-daily-rotate-file#396]
## Environment Configuration
The application is running in Docker with a volume mounted.
```Dockerfile
FROM node:20.18.0-alpine

WORKDIR /app
COPY . .

RUN npm ci

ENV NODE_ENV=docker

EXPOSE 3000
CMD ["npm", "run", "dev"]
```

```yml
backend:
    container_name: express
    build: ./backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/api/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - ./backend:/app
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-$POSTGRES_USER}?schema=public
```

Version used
```json
"dependencies": {
    "winston": "^3.15.0",
    "winston-daily-rotate-file": "^5.0.0"
  }
```

## Logger creation
```typescript
/** Utility function to generate loggers with the same format */
const generateLogger = (name: string) =>
  winston.createLogger({
    levels,
    format: winston.format.combine(
      winston.format.timestamp(),
      winston.format.label({label: name}),
      winston.format.align(),
      winston.format.errors({stack: true}),
      winston.format.printf(printfLogs),
    ),
    transports: [
      new winston.transports.DailyRotateFile({
        frequency, // 1d
        datePattern: 'YYYY-MM-DD',
        filename: `${name}-%DATE%`,
        dirname: logDirectory,
        maxSize: '1k', // Testing rotation of new file
        extension: '.log',
      }),
    ],
  });
```

## Expected behavior
Suppose we have a logger with the name `example`, we will have the first file named `generic-2024-10-30.log`, then this file exceeds the 1kB size we want to have `generic-2024-10-30.1.log`.

## Actual behavior
A file named `generic-%DATE%.1.log` is created.

## Other info
The reading and writing works without any problem, only the filename is wrong.
